/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import java.awt.Color;
import java.awt.Graphics2D;

import javax.swing.JOptionPane;

import Client.Client;

/**
 *
 * @author S401-28
 */
public class LoginFrame extends javax.swing.JFrame {

	UserDAO userDAO;
	
	/**
	 * Creates new form LoginFrame
	 */
	public LoginFrame() {
		userDAO = new UserDAO();
		
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jPanel2 = new javax.swing.JPanel();
		jTextField_Identification = new javax.swing.JTextField() {
			private int fontSize = 16;

			@Override
			protected void paintComponent(java.awt.Graphics g) {
				super.paintComponent(g);

				if (getText().isEmpty()) {
					Graphics2D g2 = (Graphics2D) g.create();
					g2.setBackground(Color.GRAY);
					g2.setColor(Color.GRAY);
					g2.setFont(new java.awt.Font("휴먼편지체", 0, fontSize));
					g2.drawString("아이디", 10, this.getHeight() / 2 + fontSize / 2); // figure out x, y from font's
																					// FontMetrics and size of
																					// component.
					g2.dispose();
				}
			}
		};
		jButton_Exit = new javax.swing.JButton();
		jButton_Login = new javax.swing.JButton();
		jPasswordField_Password = new javax.swing.JPasswordField() {
			private int fontSize = 16;

			@Override
			protected void paintComponent(java.awt.Graphics g) {
				super.paintComponent(g);

				if (String.valueOf(getPassword()).isEmpty()) {
					Graphics2D g2 = (Graphics2D) g.create();
					g2.setBackground(Color.GRAY);
					g2.setColor(Color.GRAY);
					g2.setFont(new java.awt.Font("휴먼편지체", 0, fontSize));
					g2.drawString("비밀번호", 10, this.getHeight() / 2 + fontSize / 2); // figure out x, y from font's
																					// FontMetrics and size of
																					// component.
					g2.dispose();
				}
			}
		};
		jButton_SignIn = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setUndecorated(true);
		setResizable(false);

		jPanel1.setBackground(new java.awt.Color(218, 243, 246));
		jPanel1.setPreferredSize(new java.awt.Dimension(400, 286));

		jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
		jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel1.setText("Account Login");
		jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

		jPanel2.setBackground(new java.awt.Color(218, 243, 246));

		jTextField_Identification.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
		jTextField_Identification.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField_IdentificationActionPerformed(evt);
			}
		});

		jButton_Exit.setBackground(new java.awt.Color(255, 204, 204));
		jButton_Exit.setText("종료");
		jButton_Exit.setToolTipText("");
		jButton_Exit.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton_ExitActionPerformed(evt);
			}
		});

		jButton_Login.setBackground(new java.awt.Color(179, 236, 255));
		jButton_Login.setText("로그인");
		jButton_Login.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton_LoginActionPerformed(evt);

			}
		});

		jButton_SignIn.setBackground(new java.awt.Color(204, 255, 204));
		jButton_SignIn.setText("회원가입");
		jButton_SignIn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton_SignInActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addContainerGap().addGroup(jPanel2Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jPasswordField_Password)
						.addComponent(jTextField_Identification, javax.swing.GroupLayout.Alignment.TRAILING)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
								.addComponent(jButton_Login, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jButton_SignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 90,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jButton_Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 85,
										javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addContainerGap()));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addGap(33, 33, 33)
						.addComponent(jTextField_Identification, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addComponent(jPasswordField_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jButton_Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jButton_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jButton_SignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap(20, Short.MAX_VALUE)));

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(50, 50, 50)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addContainerGap(49, Short.MAX_VALUE)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(11, 11, 11)
						.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 0, Short.MAX_VALUE)));
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addComponent(jPanel1,
								javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(0, 0, 0)));

		setSize(new java.awt.Dimension(400, 232));
		setLocationRelativeTo(null);
	}// </editor-fold>//GEN-END:initComponents

	private void jButton_ExitActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton_ExitActionPerformed
		System.exit(0);
	}// GEN-LAST:event_jButton_ExitActionPerformed

	
	//아이디 또는 비밀번호 빈칸 일 경우
	public boolean formcheck() {
		if(jPasswordField_Password.getText().toString().equals("") ||
				jTextField_Identification.getText().toString().equals("")) {
			JOptionPane.showMessageDialog(this, "아이디 혹은 비밀번호를 입력하세요.");
			return false;
		}else {
			return true;
		}
	}
		
	private void jButton_LoginActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton_LoginActionPerformed
		// TODO add your handling code here:
		// login dao check 로그인 ㅇㅋ
		String id = jTextField_Identification.getText();
		String pw = jPasswordField_Password.getText().toString();
		
		if(evt.getSource() == jButton_Login) {
			if(formcheck() == true) {
				if(userDAO.idCheck(id)) {
					if(userDAO.login(id, pw)) {
						JOptionPane.showMessageDialog(this, id + "님이 로그인하였습니다." );
						new Client(id);
						this.setVisible(false);
					}else {
						JOptionPane.showMessageDialog(this, "아이디와 비밀번호를 확인하세요");
					}
				}else {
					JOptionPane.showMessageDialog(this, "존재하지 않는 아이디 입니다.");
				}
			}
		}
		
		jTextField_Identification.setText("");
		jPasswordField_Password.setText("");
		
	}// GEN-LAST:event_jButton_LoginActionPerformed

	private void jTextField_IdentificationActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField_IdentificationActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField_IdentificationActionPerformed

	private void jButton_SignInActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton_SignInActionPerformed
		// TODO add your handling code here:
		// 회원가입 뷰 불러오기
		new SignInForm(this);
	}// GEN-LAST:event_jButton_SignInActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				LoginFrame frame = new LoginFrame();

				FrameDragListener frameDragListener = new FrameDragListener(frame);
				frame.addMouseListener(frameDragListener);
				frame.addMouseMotionListener(frameDragListener);
				frame.setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton_Exit;
	private javax.swing.JButton jButton_Login;
	private javax.swing.JButton jButton_SignIn;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPasswordField jPasswordField_Password;
	private javax.swing.JTextField jTextField_Identification;
	// End of variables declaration//GEN-END:variables
}
